# Generated by Django 3.2.3 on 2021-05-31 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviceapp', '0006_auto_20210531_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='deviceMessage',
            field=models.CharField(default='Adding new device.', max_length=100),
        ),
        migrations.AlterField(
            model_name='logdevice',
            name='LogTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 12, 58, 22, 700475)),
        ),
        migrations.AlterField(
            model_name='loguser',
            name='LogTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 12, 58, 22, 700798)),
        ),
    ]
