# Generated by Django 3.2.3 on 2021-05-31 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviceapp', '0007_auto_20210531_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='deviceMessage',
        ),
        migrations.AlterField(
            model_name='logdevice',
            name='LogTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 14, 34, 57, 742842)),
        ),
        migrations.AlterField(
            model_name='loguser',
            name='LogTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 14, 34, 57, 743160)),
        ),
    ]
