# Generated by Django 3.2.3 on 2021-05-31 14:57

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deviceapp', '0008_auto_20210531_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logdevice',
            name='LogTime',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 31, 14, 57, 11, 950901)),
        ),
        migrations.AlterField(
            model_name='loguser',
            name='LogTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
