# Generated by Django 3.2.3 on 2021-05-31 14:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deviceapp', '0009_auto_20210531_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logdevice',
            name='LogTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
