# Generated by Django 3.2.3 on 2021-05-31 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deviceapp', '0011_auto_20210531_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logdevice',
            old_name='LogDevice',
            new_name='logDevice',
        ),
        migrations.RenameField(
            model_name='logdevice',
            old_name='LogTime',
            new_name='logTime',
        ),
        migrations.RenameField(
            model_name='loguser',
            old_name='LogTime',
            new_name='logTime',
        ),
        migrations.RenameField(
            model_name='loguser',
            old_name='LogUser',
            new_name='logUser',
        ),
    ]
