# Generated by Django 3.2.3 on 2021-06-01 04:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deviceapp', '0012_auto_20210531_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logdevice',
            name='logDevice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='deviceapp.device'),
        ),
        migrations.AlterField(
            model_name='loguser',
            name='logUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to=settings.AUTH_USER_MODEL),
        ),
    ]
